version: '3'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:3002"]
      interval: 30s
      timeout: 10s
      retries: 3 