services:
  baila-bio:
    build: 
      context: .
      dockerfile: Dockerfile
    image: baila-bio:latest
    container_name: baila-bio
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - default
      - cloudflared
    volumes:
      - app-data:/app/data
    labels:
      - "com.baila.description=Baila Bio Web Application"
      - "com.baila.service=web"
      - "com.baila.engine=nodejs"

networks:
  default:
  cloudflared:
    external: true
    name: cloudflared

volumes:
  app-data:
    driver: local