services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=0
        - NODE_ENV=production
        - NPM_CONFIG_LOGLEVEL=verbose
      no_cache: true
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002"]
      interval: 30s
      timeout: 10s
      retries: 3 